server:
  port: 8888
spring:
  application:
    name: server-center
#  data.mongodb.uri: mongodb://epdev:easipass@192.168.131.243:27017/kfkDoc
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test
#    username: root
#    password:
  redis:
    host: localhost
    port: 6379
#    jedis:
#      pool:
#        max-active: 40
#        max-wait: -1
#        max-idle: 24
#        min-idle: 0
#    timeout: 3000
    cluster:
      nodes: 192.168.220.129:7000,192.168.220.129:7001,192.168.220.129:7002,192.168.220.130:7003,192.168.220.130:7004,192.168.220.130:7005



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lql.mybatis.beans

#pagehelper分页插件
pagehelper:
    helperDialect: oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 日志配置文件(直接在config处配置文件名 路径是在girl/logback-boot.xml)
#logging:
#  config: classpath:logback-boot.xml

#日志相关配置
#logging:
#  level: info
#  file: spring.log
#logging.file=shallowCopy1.log



